### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by ba-frontend-2016** [SergioBenitez/RustFS#3]
Hello, SergioBenitez!
I can't compile the library on rustc 1.8.0.
$ rustc --opt-level=3 src/proc.rs
error: Unrecognized option: 'opt-level'.
$ rustc src/proc.rs
src/inode.rs:9:21: 9:22 error: expected one of `!`, `(`, `+`, `::`, `;`, `<`, or `]`, found `,`
src/inode.rs:9 type Page = Box<([u8, ..PAGE_SIZE])>;
                                                         ^
error: aborting due to previous error

**Comment by SergioBenitez** [comment]
Thanks for the issue! I'm not sure why I didn't receive a notification of this 4 month ago! I just found it now. It should be working with the latest Rust now.
