### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by xxks-kkk** [SergioBenitez/RustFS#5]
Hello Sergio,

Tried to run the test like `RUST_TEST_THREADS=1 cargo test` under `RustFS` directory on Mac OS 10.10.5 with `rustc` version `rustc 1.27.2 (58cc626de 2018-07-18)`. The error looks like:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.43
   Compiling rand v0.4.3
   Compiling time v0.1.40
   Compiling rand v0.3.22
   Compiling rustfs v0.1.0 (file:///Users/zeyuan/Documents/projects/RustFS)
warning: static variable `test_inode_drop` should have an upper case name such as `TEST_INODE_DROP`
   --> src/lib.rs:112:3
    |
112 |   static mut test_inode_drop: bool = false;
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: #[warn(non_upper_case_globals)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 24.11s
     Running target/debug/deps/rustfs-0a853a8761bd29e2

running 7 tests
test inode::tests::test_simple_write ... error: process didn't exit successfully: `/Users/zeyuan/Documents/projects/RustFS/target/debug/deps/rustfs-0a853a8761bd29e2` (signal: 11, SIGSEGV: invalid memory reference)
```

Do you know what is `proc.rs`? I tried to run `./src/test.sh` and I get the following error message:

```
./src/test.sh
error: couldn't read "proc.rs": No such file or directory (os error 2)

error: aborting due to previous error

./src/test.sh: line 2: ./rustfs.out: No such file or directory
```

I also test on Ubuntu 16.04 and everything works. I'm wondering which part of code that relies on the Mac OS?

Thanks!

**Comment by SergioBenitez** [comment]
Coming at this a couple of years later as I'm about to archive this: it looks like something, probably in `libslab`, depends on something in the allocator, the interface of which has changed dramatically in Rust since this issue. The code is now woefully out of date. As this experiment still serves it's purpose, I'm leaving this as-is. Thanks for the report, nevertheless!
